[Definition]
# NGINX error log entries generated when limit_req is exceeded.
failregex = ^\S+ \[\w+\] \d+#\d+: \*\d+ limiting requests, excess: .* by zone "per_ip_rate", client: <HOST>, .*
ignoreregex =
